#
# Copyright (c) 2021 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e. V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix aas: <https://admin-shell.io/aas/3/0/RC02/>
prefix def: <https://admin-shell.io/aas/3/0/RC02/DataTypeDefXsd/>

template idstt:to_enum_value(?class) {
	 
	if ( str(?parent) = str(<aas:DataTypeDefXsd>), 
		if (str(?class) = str(<def:AnyUri>), "xs:anyURI", 
			CONCAT("xs:", LCASE( SUBSTR( ?localName, 1, 1)), SUBSTR( ?localName, 2))
		),
		st:call-template(idstt:to_class_name, ?class)
	)

}
where {
	?class rdf:type ?parent . 
	BIND( st:call-template(idstt:to_class_name, ?class) AS ?localName)
}
